import { GET_USERS } from "../constants/query";

export const mocks = [
  {
    request: {
      query: GET_USERS,
      variables: { search: "", sortBy: "name", sortOrder: "asc" },
    },
    result: {
      data: {
        users: [
          {
            id: "5",
            name: "Chelsey Dietrich",
            username: "Kamren",
            email: "Lucio_Hettinger@annie.ca",
            address: {
              street: "Skiles Walks",
              suite: "Suite 351",
              city: "Roscoeview",
              zipcode: "33263",
              __typename: "Address",
            },
            phone: "(254)954-1289",
            website: "demarco.info",
            company: {
              name: "Keebler LLC",
              catchPhrase: "User-centric fault-tolerant solution",
              bs: "revolutionize end-to-end systems",
              __typename: "Company",
            },
            __typename: "User",
          },
          {
            id: "10",
            name: "Clementina DuBuque",
            username: "Moriah.Stanton",
            email: "Rey.Padberg@karina.biz",
            address: {
              street: "Kattie Turnpike",
              suite: "Suite 198",
              city: "Lebsackbury",
              zipcode: "31428-2261",
              __typename: "Address",
            },
            phone: "024-648-3804",
            website: "ambrose.net",
            company: {
              name: "Hoeger LLC",
              catchPhrase: "Centralized empowering task-force",
              bs: "target end-to-end models",
              __typename: "Company",
            },
            __typename: "User",
          },
          {
            id: "3",
            name: "Clementine Bauch",
            username: "Samantha",
            email: "Nathan@yesenia.net",
            address: {
              street: "Douglas Extension",
              suite: "Suite 847",
              city: "McKenziehaven",
              zipcode: "59590-4157",
              __typename: "Address",
            },
            phone: "1-463-123-4447",
            website: "ramiro.info",
            company: {
              name: "Romaguera-Jacobson",
              catchPhrase: "Face to face bifurcated interface",
              bs: "e-enable strategic applications",
              __typename: "Company",
            },
            __typename: "User",
          },
          {
            id: "2",
            name: "Ervin Howell",
            username: "Antonette",
            email: "Shanna@melissa.tv",
            address: {
              street: "Victor Plains",
              suite: "Suite 879",
              city: "Wisokyburgh",
              zipcode: "90566-7771",
              __typename: "Address",
            },
            phone: "010-692-6593 x09125",
            website: "anastasia.net",
            company: {
              name: "Deckow-Crist",
              catchPhrase: "Proactive didactic contingency",
              bs: "synergize scalable supply-chains",
              __typename: "Company",
            },
            __typename: "User",
          },
          {
            id: "9",
            name: "Glenna Reichert",
            username: "Delphine",
            email: "Chaim_McDermott@dana.io",
            address: {
              street: "Dayna Park",
              suite: "Suite 449",
              city: "Bartholomebury",
              zipcode: "76495-3109",
              __typename: "Address",
            },
            phone: "(775)976-6794 x41206",
            website: "conrad.com",
            company: {
              name: "Yost and Sons",
              catchPhrase: "Switchable contextually-based project",
              bs: "aggregate real-time technologies",
              __typename: "Company",
            },
            __typename: "User",
          },
          {
            id: "7",
            name: "Kurtis Weissnat",
            username: "Elwyn.Skiles",
            email: "Telly.Hoeger@billy.biz",
            address: {
              street: "Rex Trail",
              suite: "Suite 280",
              city: "Howemouth",
              zipcode: "58804-1099",
              __typename: "Address",
            },
            phone: "210.067.6132",
            website: "elvis.io",
            company: {
              name: "Johns Group",
              catchPhrase: "Configurable multimedia task-force",
              bs: "generate enterprise e-tailers",
              __typename: "Company",
            },
            __typename: "User",
          },
          {
            id: "1",
            name: "Leanne Graham",
            username: "Bret",
            email: "Sincere@april.biz",
            address: {
              street: "Kulas Light",
              suite: "Apt. 556",
              city: "Gwenborough",
              zipcode: "92998-3874",
              __typename: "Address",
            },
            phone: "1-770-736-8031 x56442",
            website: "hildegard.org",
            company: {
              name: "Romaguera-Crona",
              catchPhrase: "Multi-layered client-server neural-net",
              bs: "harness real-time e-markets",
              __typename: "User",
            },
            __typename: "User",
          },
          {
            id: "6",
            name: "Mrs. Dennis Schulist",
            username: "Leopoldo_Corkery",
            email: "Karley_Dach@jasper.info",
            address: {
              street: "Norberto Crossing",
              suite: "Apt. 950",
              city: "South Christy",
              zipcode: "23505-1337",
              __typename: "Address",
            },
            phone: "1-477-935-8478 x6430",
            website: "ola.org",
            company: {
              name: "Considine-Lockman",
              catchPhrase: "Synchronised bottom-line interface",
              bs: "e-enable innovative applications",
              __typename: "Company",
            },
            __typename: "User",
          },
          {
            id: "8",
            name: "Nicholas Runolfsdottir V",
            username: "Maxime_Nienow",
            email: "Sherwood@rosamond.me",
            address: {
              street: "Ellsworth Summit",
              suite: "Suite 729",
              city: "Aliyaview",
              zipcode: "45169",
              __typename: "Address",
            },
            phone: "586.493.6943 x140",
            website: "jacynthe.com",
            company: {
              name: "Abernathy Group",
              catchPhrase: "Implemented secondary concept",
              bs: "e-enable extensible e-tailers",
              __typename: "Company",
            },
            __typename: "User",
          },
          {
            id: "4",
            name: "Patricia Lebsack",
            username: "Karianne",
            email: "Julianne.OConner@kory.org",
            address: {
              street: "Hoeger Mall",
              suite: "Apt. 692",
              city: "South Elvis",
              zipcode: "53919-4257",
              __typename: "Address",
            },
            phone: "493-170-9623 x156",
            website: "kale.biz",
            company: {
              name: "Robel-Corkery",
              catchPhrase: "Multi-tiered zero tolerance productivity",
              bs: "transition cutting-edge web services",
              __typename: "Company",
            },
            __typename: "User",
          },
        ],
      },
    },
  },
];
